arb-dir: lib/l10n
template-arb-file: app_ar.arb
output-class: ReadyExtensionLocalizations
output-localization-file: ready_extension_localizations.dart
untranslated-messages-file: untranslated.json
output-dir: lib/src/messages
synthetic-package: false
