name: ready_extensions
description: Collection of extension methods to make your code simple , clean and fast
version: 1.3.0-dev-2
homepage: https://github.com/mo-ah-dawood/ready/tree/main/packages/ready_extensions
repository: https://github.com/mo-ah-dawood/ready
issue_tracker: https://github.com/mo-ah-dawood/ready/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  ready_extensions_dart: ^1.3.0-dev-2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: false
