name: ready
description: Package that contains complete list solution and admin dashboard
version: 2.2.0
homepage: https://github.com/mo-ah-dawood/ready

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  equatable: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  bloc: ^8.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
