arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-class: ReadyValidationMessages
output-localization-file: messages.dart
untranslated-messages-file: untranslated.json
output-dir: lib/src/messages
synthetic-package: false

header: |
  // cSpell: disable
  // ignore_for_file: unused_local_variable, unnecessary_brace_in_string_interps, equal_keys_in_map, unnecessary_string_interpolations, no_leading_underscores_for_local_identifiers
