name: ready_validation
description: Collection of extension methods to make validation simple , clean and fast
version: 2.2.0
homepage: https://github.com/mo-ah-dawood/ready/tree/main/packages/ready_validation
repository: https://github.com/mo-ah-dawood/ready
issue_tracker: https://github.com/mo-ah-dawood/ready/issues

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ready_extensions: ^1.0.8
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
