name: ready_form
description: Package that help to manage forms
version: 1.0.16
homepage: https://github.com/mo-ah-dawood/ready/tree/main/packages/ready_form
repository: https://github.com/mo-ah-dawood/ready
issue_tracker: https://github.com/mo-ah-dawood/ready/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
