name: ready_form
description: Package that help to manage forms
version: 0.0.13
homepage: https://github.com/mo-ah-dawood/ready/tree/main/packages/ready_form
repository: https://github.com/mo-ah-dawood/ready
issue_tracker: https://github.com/mo-ah-dawood/ready/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
