name: ready_picker
description: Pop up picker that uses ready controllers
version: 0.0.1
homepage: https://github.com/mo-ah-dawood/ready

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ready: ^0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
